Paginate = 10
baseurl = "https://linkerd.io/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
languageCode = "en-US"
sectionPagesMenu = "main"
theme = "buoyant"
title = "Linkerd"
[blackfriday]
HrefTargetBlank = true
[mediaTypes."text/netlify"]
delimiter = ""
[[menu.community]]
name = "Slack"
url = "https://slack.linkerd.io/"
weight = 3
[[menu.community]]
name = "Discourse"
url = "https://discourse.linkerd.io/"
weight = 2
[[menu.community]]
name = "GitHub"
url = "https://github.com/linkerd/linkerd2"
weight = 1
[[menu.follow]]
name = "Twitter"
url = "https://twitter.com/linkerd"
weight = 3
[[menu.follow]]
name = "YouTube"
url = "https://www.youtube.com/buoyantio"
weight = 1
[[menu.top]]
identifier = "documentation"
name = "Docs"
url = "/docs/"
weight = 1
[[menu.top]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 3
[[menu.top]]
identifier = "github"
name = "GitHub"
pre = "<i class='fab fa-github fa-lg' aria-hidden='true'></i>"
url = "https://github.com/linkerd/linkerd2"
weight = 5
[[menu.top]]
identifier = "start"
name = "GET STARTED"
post = "</span>"
pre = "<span class='button-spacer'>"
url = "/2/getting-started/"
weight = 6
[outputFormats.REDIRECTS]
baseName = "_redirects"
mediaType = "text/netlify"
[outputs]
home = ["HTML", "REDIRECTS"]
section = ["HTML", "JSON"]
[params]
description = "Linkerd is a service mesh for Kubernetes and beyond. It gives you observability, reliability, and security without requiring any changes to your code."
images = [""]
l5d2_edge_version = "L5D2_EDGE_VERSION"
l5d2_release_version = "L5D2_STABLE_VERSION"
latest_release_date = "2019-02-01"
latest_release_version = "1.6.1"
logo = "/images/identity/svg/linkerd_primary_color_white.svg"
[permalinks]
blog = "/:year/:month/:day/:slug/"
[privacy.twitter]
disable = false
enableDNT = false
simple = false
