[build]
base = "linkerd.io"
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.74.3"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
  from = "/enterprise"
  to = "/support-training/"
  status = 301
