# Minimum version of Hugo required to build linkerd.io
minHugoVersion: "0.131.0"

# Open Graph and Twitter Card defaults
description: |-
  Linkerd is an ultralight service mesh for Kubernetes. It gives you
  observability, reliability, and security without requiring any code changes.
#images: [/logos/linkerd.png]

# Set the value of `twitter:site` in Twitter Card
social:
  twitter: Linkerd

# Latest majar version of Linkerd
latestMajorVersion: "2.16"
