---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/authors.json
  label: Authors
  match: "**/*"
- type: directory
  path: linkerd.io/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: linkerd.io/content/dashboard
  label: Dashboard
  create: all
  match: "**/*"
- type: directory
  path: linkerd.io/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: linkerd.io/content/2
  label: Linkerd 2 Docs
  create: all
  match: "**/*"
- type: directory
  path: linkerd.io/content/1
  label: Linkerd 1 Docs
  create: all
  match: "**/*"
upload_dir: linkerd.io/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
version: 0.54.0
