name: check

on:
  pull_request_target:
    paths:
      - linkerd.io/**

jobs:
  linkerd_io:
    name: check source files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Markdown SEO Check
        uses: zentered/markdown-seo-check@v1.1.3
        with:
          includes: '/linkerd.io/content/**/*.md'
          max_title_length: 70
          max_description_length: 150
          max_slug_length: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
