name: check

on:
  pull_request:
    paths:
      - linkerd.io/**

jobs:
  linkerd_io:
    name: check source files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Markdown SEO Check
        uses: zentered/markdown-seo-check@v1.1.2
        with:
          includes: '/linkerd.io/content/**/*.md'
          max_title_length: 70
          max_description_length: 150
          max_slug_length: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
