name: publish

on:
  push:
    branches:
    - main
  repository_dispatch:
    types: [release]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: linkerd/dev/actions/setup-tools@v47
    - name: Checkout code
      uses: actions/checkout@v5

    - name: On create
      run: |
        .devcontainer/on-create.sh

    - name: Setup gcloud
      env:
        LINKERD_SITE_TOKEN: ${{ secrets.LINKERD_SITE_TOKEN }}
      run: |-
        echo "${LINKERD_SITE_TOKEN}" | base64 -d > .gcp.json
        gcloud auth activate-service-account --key-file=.gcp.json

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        make publish
        gsutil -m setmeta -r -h "Cache-Control: no-cache, no-store, must-revalidate" gs://linkerd.io/
        gsutil -m setmeta -r -h "Cache-Control:" gs://linkerd.io/
