name: publish

on:
  push:
    branches:
    - main
  repository_dispatch:
    types: [release]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    container:
      image: buoyantio/website-builder:v1.3.3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup gcloud
      env:
        LINKERD_SITE_TOKEN: ${{ secrets.LINKERD_SITE_TOKEN }}
      run: |-
        echo "${LINKERD_SITE_TOKEN}" | base64 -d > .gcp.json
        gcloud auth activate-service-account --key-file=.gcp.json

    - name: Publish
      run: |-
        make publish
