name: validate

on:
  pull_request:
    paths:
    - linkerd.io/**

jobs:
  linkerd_io:
    name: Validate generated HTML
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/linkerd/dev:v39
      options: --user root
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: On create
      run: |
        .devcontainer/on-create.sh

    - name: Lint markdown
      run: |
        make lint

    - name: Lint html and check for dead links
      run: |
        make check
