name: validate

on:
  pull_request:
    paths:
      - linkerd.io/**

jobs:
  linkerd_io:
    name: Validate generated HTML
    runs-on: ubuntu-18.04
    container:
      image: buoyantio/website-builder:v1.3.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Lint markdown
        run: |
          make lint

      - name: Lint html and check for dead links
        run: |
          make check

      - name: Markdown SEO Check
        uses: zentered/markdown-seo-check@v1.1.0
        with:
          includes: '/linkerd.io/content/**/*.md'
          max_title_length: 70
          max_description_length: 150
          max_slug_length: 100
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
